### ISSUE TITLE
final_result is size of 17*5, why?

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [HRNet/Higher-HRNet-Human-Pose-Estimation#22]
Hi guys,
What are the five values of each point exactlly represent for ?

**Comment by zhezh** [comment]
Hi @Zhaoyi-Yan ,
have you figured out all these 5 dimensions' meanings?
could you share you findings
Thanks

**Comment by Zhaoyi-Yan** [comment]
(x, y, z, trans_x, trans_y), the last two values are params of transformation matrix.

**Comment by zhezh** [comment]
@Zhaoyi-Yan  great, thanks

**Comment by Crophone** [comment]
would you please tell me what's the meaning of z ? @Zhaoyi-Yan
