### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by jevonswang** [HRNet/Higher-HRNet-Human-Pose-Estimation#4]
Hi,
   What kind of GPU do you use? I trained with 1080Ti, but got "CUDA out of memory" error, even the batchsize is 1 and FP16 enabled. What should I do next to train my own model?

**Comment by bowenc0221** [comment]
We used P100 to train our models.  
What is your cfg file?

**Comment by jevonswang** [comment]
> We used P100 to train our models.
> What is your cfg file?

My cfg is w32_512_adam_lr1e-3.yaml, where IMAGES_PER_GPU is modified to 1. P100 has 16GB memory while 1080Ti has only 11GB. I'm trying to cut down channels to reduce the memory needed. Thanks for your relpy.

**Comment by jevonswang** [comment]
Sorry, I made a mistake. 
Although I set CUDA_VISIBLE_DEVICES=3, but MULTIPROCESSING_DISTRIBUTED is true, so it still run at the first GPU, which is already occupied by others.

**Comment by WinstonDeng** [comment]
@jevonswang Hi, how to fix it? I met same error. My env is 2*1080Ti. Even though setting train_batch=1 and num_worker=2, it is still out of memory.
