### ISSUE TITLE
Questions regarding inference code

### ISSUE THREAD

**Issue by ADulian** [HRNet/Higher-HRNet-Human-Pose-Estimation#91]
Hello,

I have several questions regarding the validation of the model and I hope you will be able to address them.

1. Why is the training performed on an image of shape `512*512` but when tested only the shorter side has a length `512`?

- `resize_align_multi_scale(*)` -> `get_multi_scale_size(*)`:

1. According to the following `int((min_scale * input_size + 63)//64 * 64)` the computed shape will be a multiple of 64, is there a specific reason for this choice?
2. In the paper section "4. Testing" you state that "We first resize the short side of the input image to 512 and keep the aspect ratio", however, due to the shape computation (point 1) this does not hold true for all cases. E.g. let the input image be of shape (h=427, w=640) w/h = ~1.5, the resized image will then have a shape of (h=512, w=768) w/h = ~ 1.5. If however we assume the initial image shape is (h=427, w=642) w/h = ~1.5, then the resized image will have a shape of (h=512, w=832) w/h = ~1.62. I do realise that this might be a trivial difference, just wanted to confirm whether this is intentional, and whether it could possibly cause further issues with regards to prediction?
3.  `scale_h, scale_w` are both `/ 200` but when both scales are passed to `get_affine_transform(*)` the reverse happens i.e. both are rescaled by `* 200.` I do not see the `scale/200` being used anywhere else in the function and I therefore wonder if this step is redundant, or whether there is a specific purpose for it?
 
- `parse(*)` -> `top_k(*)`:

1. Why is pooling used as a choice for NMS? And is there any specific reason for `kernel=5` and `padding=2`, I believe its purpose is to preserve the shape of the input map, if so, would the use of `kernel=3` and` padding=1` be also a valid choice?
2. The `max_num_people=30`, is there a specific reason why this is set to 30, or is this just a number that is based on empirical evaluation as to cover the max number of people that might appear with respect to COCO images? If so, would reducing/increasing this number for own dataset have any effect on the output?
3. In class `Params` there is a `joint_order` array `self.joint_order = [i-1 for i in [1, 2, 3, 4, 5, 6, 7, 12, 13, 8, 9, 10, 11, 14, 15, 16, 17]]`, I see that the order refers to the joint order, however I'm unsure where does this specific order comes from?

- `parse(*)` -> `match(*)` -> `match_by_tag(*)`:

1. What is the reasoning behind the choice of threshold values for `detection_threshold=0.1` and `tag_threshold=1.0`?
2. Would you be able to briefly explain how the actual  function `match_by_tag(*)` works?

- `parse(*)` -> `adjust(*)` and `'refine(*)`:

1. What is the actual purpose of  `adjust(*)`?
2. How does `refine(*)` actually work?

Sorry for the long post, please bare in mind I have a limited experience in the area (just getting into keypoint prediction) and therefore some of the questions might be absolutely trivial to answer (I hope). Anyway, thank you in advance for your help, it's a great piece of work with some really awesome insights!

**Comment by captainjun** [comment]
yes, good
